language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
script:
    - python manage.py migrate
    - python manage.py test
before_script:
    - psql -U postgres -c "CREATE USER modeemintternet WITH PASSWORD 'modeemintternetonparraim';"
    - psql -U postgres -c "ALTER USER modeemintternet CREATEDB;"
    - psql -U postgres -c "CREATE DATABASE modeemintternet ENCODING 'UTF8' OWNER modeemintternet;"
