language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
    - psql -U postgres -c "CREATE USER modeemintternet WITH PASSWORD 'modeemintternetonparraim';"
    - psql -U postgres -c "ALTER USER modeemintternet CREATEDB;"
    - psql -U postgres -c "CREATE DATABASE modeemintternet ENCODING 'UTF8' OWNER modeemintternet;"
script:
    - python manage.py migrate
    - coverage run --source=modeemintternet manage.py test
after_success:
    - coveralls
